/* tslint:disable */
/* eslint-disable */
/**
 * Check man Search engine REST API documentation
 * Official REST documentation for search engine using Elastic search.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: ondrej.chrbolka@upce.cz
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */export * from './apis/feedback-search-v1-api';

